"""
Export Engine for Narrative Simulation.
Generates beautifully formatted Markdown and Text bundles.
Phase 9 Enhancement: WorldState-integrated export.
"""

import os
from datetime import datetime
from typing import List, Dict, Any, Optional


def generate_markdown(scenes, lead_char=None, story_context=None):
    """
    scenes: list of dicts with 'scene_number', 'text', 'metadata'
    lead_char: dict of lead character attributes
    story_context: dict with 'genre', 'plot'
    """
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")
    
    lines = []
    lines.append(f"# 🎬 Cinematic Narrative: {story_context.get('genre', 'Untitled Story') if story_context else 'Untitled Story'}")
    lines.append(f"*Generated on: {timestamp}*")
    lines.append("\n---\n")
    
    # 1. Casting & Production Notes
    lines.append("## 🎞️ Production Notes")
    if story_context:
        lines.append(f"**줄거리**: {story_context.get('plot')}")
    
    if lead_char:
        lines.append("\n### 🎭 Main Cast")
        lines.append(f"- **{lead_char.get('name')}** (나이: {lead_char.get('age')}, MBTI: {lead_char.get('mbti')})")
        lines.append(f"  - 직업: {lead_char.get('occupation')}")
        lines.append(f"  - 성격: {lead_char.get('personality')}")
        lines.append(f"  - 치명적 단점: {lead_char.get('flaw')}")
        lines.append(f"  - 특별 스킬: {lead_char.get('skill')}")
    
    lines.append("\n---\n")
    
    # 2. Scenes
    lines.append("## 📽️ Scenes")
    for s in scenes:
        meta = s.get("metadata", {})
        place = meta.get("place", "알 수 없음")
        tag = meta.get("tag", "NORMAL")
        
        lines.append(f"### SCENE {s['scene_number']} - [{place} / {tag}]")
        lines.append(f"\n{s['text']}\n")
        
    lines.append("\n---\n")
    lines.append("*End of Storyboard. Generated by Antigravity Cinematic Engine*")
    
    return "\n".join(lines)


def generate_text_bundle(scenes):
    """Generates a plain text bundle for easy copy-pasting."""
    output = []
    for s in scenes:
        output.append(f"[{s['scene_number']}씬]\n{s['text']}\n")
    return "\n".join(output)


def save_to_file(content, filename):
    """Saves content to a temporary file for delivery."""
    os.makedirs("outputs", exist_ok=True)
    path = os.path.join("outputs", filename)
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    return os.path.abspath(path)


# --- Phase 9: WorldState-Integrated Export ---

def from_world_state(state, title: str = None) -> str:
    """
    Phase 9: Directly exports a WorldState to a full Markdown screenplay.
    Priority: rendered_scenes (full AI text) > story_beats (summary fallback)
    """
    from .render_engine import RenderEngine
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")
    project_title = title or state.metadata.get("summary", "Untitled Narrative")
    lead = state.lead_character

    lines = [
        f"# 🎬 {project_title}",
        f"*Infinite Narrative Canvas V2 | Exported: {timestamp}*",
        "\n---\n",
    ]

    # Production Notes: Lead Character
    if lead:
        lines.append("## 🎭 Main Cast")
        lines.append(f"- **{lead.get('name', '?')}** | {lead.get('mbti', '?')} | {lead.get('occupation', '?')}")
        lines.append(f"  - 성격: {lead.get('personality', '?')}")
        lines.append(f"  - 치명적 단점: {lead.get('flaw', '?')}")
        lines.append(f"  - 특별 스킬: {lead.get('skill', '?')}")
        lines.append("\n---\n")

    # System Status
    lines.append("## 📊 Narrative Status")
    lines.append(f"- 추진력(Momentum): {state.momentum_level:.1f}x")
    lines.append(f"- 서사 진단: {state.narrative_ailment}")
    lines.append(f"- 타임라인 모드: {state.timeline_mode}")
    lines.append("\n---\n")

    # Scenes: iterate through story_beats and use rendered text where available
    beats = state.story_beats
    rendered_map = {s.get("beat_index"): s for s in state.rendered_scenes}

    lines.append("## 📽️ Screenplay")

    if beats:
        from .blueprint_engine import BlueprintEngine
        for i, beat in enumerate(beats):
            lines.append(f"\n### SCENE {i + 1}: {beat.get('title', 'Untitled')}")
            
            # Use rendered text if it exists for this beat index
            if i in rendered_map:
                scene = rendered_map[i]
                lines.append(scene.get("scene_text", ""))
            else:
                # Fallback: build structured scene from beat summary + blueprint
                content = beat.get("content", "")
                spec = BlueprintEngine.generate_visual_spec(content, state.momentum_level)
                lines.append(f"\n{content}\n")
                lines.append(f"**[콘티]** {spec['shot_type']} | {spec['lighting']} | {spec['movement']}")
                lines.append(f"\n**[Visual Prompt]**\n> {spec['image_prompt']}")
            
            lines.append("\n---")
    else:
        lines.append("\n*아직 커밋된 서사 비트가 없습니다.*\n")

    lines.append("\n*End of Screenplay — Infinite Narrative Canvas*")
    return "\n".join(lines)


def export_world_state_to_file(state, title: str = None) -> str:
    """Exports WorldState to a .md file and returns the absolute path."""
    content = from_world_state(state, title)
    safe_title = (title or "narrative").replace(" ", "_").replace("/", "-")
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"{safe_title}_{timestamp}.md"
    return save_to_file(content, filename)

